# Generated by Django 5.1.4 on 2025-01-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='title',
        ),
    ]
